In [1]:
#load and print D.npy
import numpy as np
D = np.load('D.npy')
print(D)

[[1.39235356e-02 4.83210120e+00 1.03839705e+00]
 [2.61464083e-03 5.09359573e+00 9.09090909e-01]
 [1.16434752e-02 6.04058615e+00 1.02634670e+00]
 [5.00543203e-03 7.12301264e+00 9.06040268e-01]
 [3.91534692e-03 4.57548909e+00 9.09228671e-01]
 [7.24518092e-03 6.61874285e+00 9.35718809e-01]
 [5.02728276e-03 6.10751806e+00 9.05625858e-01]
 [6.54201093e-03 5.23018524e+00 9.12156983e-01]
 [1.35171598e-02 9.68319916e+00 7.58172172e-01]
 [1.42159115e-02 6.73617216e+00 8.53658537e-01]
 [1.47934719e-02 3.60574607e+00 1.05673640e+00]
 [7.85881010e-03 8.97712426e+00 9.62012827e-01]
 [9.03948507e-03 6.37604783e+00 1.06909091e+00]
 [1.60578228e-02 4.80932101e+00 8.95295903e-01]
 [1.01207218e-02 6.72500695e+00 1.06700000e+00]
 [1.17194518e-02 2.42525322e+00 1.07946473e+00]
 [2.48256543e-03 8.11166107e+00 9.09504320e-01]
 [1.61096268e-02 3.13170779e+00 1.03522899e+00]
 [8.15607092e-03 2.06415259e+00 9.12419896e-01]
 [1.20101353e-02 4.05559666e+00 1.06878130e+00]
 [1.33890822e-02 2.79045405e+00 1.080193

In [3]:
# find the maximum value in the last column in the last 20 rows
print(np.max(D[-20:, -1]))

1.0335518384587237


#