In [1]:
#load and print D.npy
import numpy as np
D = np.load('D.npy')
print(D)

[[3.98398360e-03 9.11727114e+00 8.00960735e-01]
 [4.70860498e-03 3.38603163e+00 8.03262481e-01]
 [9.98019740e-03 8.51563787e+00 1.01923781e+00]
 [3.64116123e-03 6.35652704e+00 8.08860129e-01]
 [9.31763323e-03 7.47131924e+00 1.04877893e+00]
 [1.21609203e-02 4.03797610e+00 1.06755011e+00]
 [1.62339689e-02 7.84971261e+00 7.61662613e-01]
 [1.38673297e-02 2.74676231e+00 1.07825067e+00]
 [1.68680510e-02 8.47496945e+00 7.42578386e-01]
 [4.38144707e-03 7.49306716e+00 8.07495422e-01]
 [6.74853366e-03 4.87823677e+00 8.05841278e-01]
 [1.37543808e-02 3.10388900e+00 1.06887544e+00]
 [1.37695276e-02 2.10582417e+00 1.07825067e+00]
 [6.47162001e-03 5.39334463e+00 8.09896273e-01]
 [8.94038135e-03 4.50801551e+00 9.04320988e-01]
 [1.48985140e-02 2.49737997e+00 1.07168700e+00]
 [1.59502295e-02 2.01321697e+00 1.06226665e+00]
 [4.03888943e-03 2.38150891e+00 8.02469136e-01]
 [1.15106944e-02 6.93884995e+00 1.02873668e+00]
 [1.45046874e-02 4.00548794e+00 1.02324911e+00]
 [5.29858488e-04 6.92346362e+00 8.024691

In [2]:
# find the maximum value in the last column in the last 20 rows
print(np.max(D[-20:, -1]))

1.0678321933851014
